version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: ELASTICSEARCH_HOSTS
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: ACCOUNT_SERVICE_TOKEN
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch